// Generated by CoffeeScript 1.10.0
(function() {
  var EventEmitter, MeteorMongodb, expect, ps,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  expect = require('chai').expect;

  EventEmitter = require('events').EventEmitter;

  ps = require('psext');

  MeteorMongodb = (function(superClass) {
    extend(MeteorMongodb, superClass);

    MeteorMongodb.prototype.mongodChilds = [];

    MeteorMongodb.prototype.killed = false;

    function MeteorMongodb(meteorPid) {
      this.meteorPid = meteorPid;
      log.debug("MeteorMongodb.constructor()", arguments);
      process.on('exit', (function(_this) {
        return function(code) {
          log.debug("MeteorMongodb.process.on 'exit': code=" + code);
          return _this.kill();
        };
      })(this));
      this.findAllChildren();
    }

    MeteorMongodb.prototype.hasMongodb = function() {
      log.debug("MeteorMongodb.hasMongodb()");
      return this.mongodChilds.length > 0;
    };

    MeteorMongodb.prototype.findAllChildren = function() {
      log.debug("MeteorMongodb.findAllChildren()", arguments);
      if (process.platform === 'win32') {
        return this.getChildProcessOnWindows(this.meteorPid, function(childsPid, _this) {
          _this.meteorPid = childsPid[0].pid;
          log.debug("@meteorPid", _this.meteorPid);
          return _this.getChildProcessOnWindows(childsPid[0].pid, function(childsPid, _this) {
            return _this.mongodChilds = childsPid;
          });
        });
      } else {
        log.debug("@meteorPid", this.meteorPid);
        return ps.lookup({
          command: 'mongod',
          psargs: '-l',
          ppid: this.meteorPid
        }, (function(_this) {
          return function(err, resultList) {
            var ref;
            _this.mongodChilds = resultList;
            if (err) {
              return log.warn("spacjam: Warning: Couldn't find any mongod children:\n", err);
            } else if (resultList.length > 1) {
              return log.warn("spacjam: Warning: Found more than one mongod child:\n", resultList);
            } else {
              return log.debug("Found meteor mongod child with pid: ", (ref = resultList[0]) != null ? ref.pid : void 0);
            }
          };
        })(this));
      }
    };

    MeteorMongodb.prototype.getChildProcessOnWindows = function(processPid, onSuccess) {
      var bat, resultList;
      resultList = [];
      bat = require('child_process').spawn('cmd.exe', ['/c', __dirname + "\\get_children.bat " + processPid]);
      bat.stdout.setEncoding("utf8");
      bat.stderr.setEncoding("utf8");
      bat.stdout.on('data', function(data) {
        var childPid;
        childPid = data.toString().trim();
        return resultList.push({
          pid: parseInt(childPid)
        });
      });
      bat.stderr.on('data', function(data) {
        return log.warn('spacejam: Warning: Error enumerating process children:\n', data);
      });
      return bat.on('exit', (function(_this) {
        return function(code) {
          if (code !== 0) {
            return log.warn('spacejam: Warning: Enumerating child process returned with error code: ', code);
          }
          log.debug('MongoDB children:\n', resultList);
          if (resultList.length === 0) {
            return log.warn('spacejam: Warning: Couldn\'t find any child process :\n', err);
          } else if (resultList.length > 1) {
            log.warn('spacejam: Warning: Found more than one child process :\n', resultList);
            return onSuccess(resultList, _this);
          } else {
            log.debug('Found meteor child process with pid: ', resultList[0].pid);
            return onSuccess(resultList, _this);
          }
        };
      })(this));
    };

    MeteorMongodb.prototype.kill = function() {
      var attempts, interval, onInterval;
      log.debug("MeteorMongodb.kill() killed=", this.killed);
      if (this.killed) {
        return;
      }
      this.killed = true;
      attempts = 1;
      interval = null;
      onInterval = (function(_this) {
        return function() {
          var allDead, e, error, i, j, len, len1, mongod, ref, ref1, signal;
          if (attempts <= 40) {
            signal = 0;
            if (attempts === 1) {
              signal = "SIGTERM";
            } else if (attempts === 20) {
              signal = "SIGKILL";
            }
            try {
              ref = _this.mongodChilds;
              for (i = 0, len = ref.length; i < len; i++) {
                mongod = ref[i];
                if (mongod.dead == null) {
                  try {
                    process.kill(mongod.pid, signal);
                  } catch (error) {
                    e = error;
                    mongod.dead = true;
                  }
                }
              }
              allDead = true;
              ref1 = _this.mongodChilds;
              for (j = 0, len1 = ref1.length; j < len1; j++) {
                mongod = ref1[j];
                if (mongod.dead == null) {
                  allDead = false;
                  return;
                }
              }
              if (allDead) {
                clearInterval(interval);
                _this.emit("kill-done", null, _this.mongodChilds);
              }
            } catch (undefined) {}
            return attempts++;
          } else {
            clearInterval(interval);
            log.error("spacejam: Error: Unable to kill all mongodb children, even after 40 attempts");
            return _this.emit("kill-done", new Error("Unable to kill all mongodb children, even after 40 attempts"), _this.mongodChilds);
          }
        };
      })(this);
      onInterval();
      return interval = setInterval(onInterval, 100);
    };

    return MeteorMongodb;

  })(EventEmitter);

  module.exports = MeteorMongodb;

}).call(this);
